language: objective-c
jdk:
- oraclejdk7
install:
- ANDROID_SDK_PACKAGE=android-sdk_r24.0.1-macosx.zip
- ANDROID_NDK_PACKAGE=android-ndk-r8c-darwin-x86.tar.bz2
- export TITANIUM_ANDROID_API="21"
- 
- brew update
- brew install jq
- brew install scons
- 
- sudo npm install -g titanium
- 
- export TITANIUM_ROOT=`ti sdk list -o json | jq -r '.defaultInstallLocation'`
- export TITANIUM_SDK=`ti sdk list -o json | jq -r '.installed[.activeSDK]'`
- mkdir -p "$TITANIUM_ROOT/sdks/"
- 
- export SDKS="$TRAVIS_BUILD_DIR/sdks"
- echo $SDKS
- mkdir -p "$SDKS"
- if [ ! -d "$SDKS/android-sdk-macosx" ]; then cd "$SDKS"; wget http://dl.google.com/android/$ANDROID_SDK_PACKAGE;
  unzip -o $ANDROID_SDK_PACKAGE; fi
- export ANDROID_SDK=${PWD}/android-sdk-macosx
- export PATH=${PATH}:${ANDROID_SDK}/tools:${ANDROID_SDK}/platform-tools
- 
- 
- echo yes | android -s update sdk --no-ui --all --filter tools
- echo yes | android -s update sdk --no-ui --all --filter platform-tools
- echo yes | android -s update sdk --no-ui --all --filter extra-android-support
- echo yes | android -s update sdk --no-ui --all --filter android-8
- echo yes | android -s update sdk --no-ui --all --filter android-10
- echo yes | android -s update sdk --no-ui --all --filter android-$TITANIUM_ANDROID_API
- echo yes | android -s update sdk --no-ui --all --filter addon-google_apis-google-$TITANIUM_ANDROID_API
- 
- 
- if [ ! -d "$SDKS/android-ndk-r8c" ]; then wget http://dl.google.com/android/ndk/$ANDROID_NDK_PACKAGE;
  tar xzf $ANDROID_NDK_PACKAGE; fi
- export ANDROID_NDK=${PWD}/android-ndk-r8c
- 
- 
- git clone https://github.com/ingo/titanium_build.git "$SDKS/titanium_build"
- ls "$SDKS/titanium_build"
- 
- sudo easy_install pyyaml
- sudo easy_install Pygments
- 
- export ANDROID_PLATFORM=$ANDROID_SDK/platforms/android-$TITANIUM_ANDROID_API
- export GOOGLE_APIS=$ANDROID_SDK/add-ons/addon-google_apis-google-$TITANIUM_ANDROID_API
script:
- export TITANIUM_BUILD="$SDKS/titanium_build"
- echo $TITANIUM_BUILD
- cd $TRAVIS_BUILD_DIR
- source $TITANIUM_BUILD/mobile/driver_travis.sh $TRAVIS_BRANCH
- npm install
- npm test
- ls dist
deploy:
  provider: releases
  api_key:
    secure: q8aTFLKhQA0PFa5iRhe6kERbLs+xdFs0DBC1gOiN5kAuePREbwGW/7AZtD0EUoShH3KdG7uV4np2qVVz/S+Ze/aBhlVXyfTz7BZrEKBwpY7fFbf5+cWg2R9aWLHg14oNY19zuBnFOYY+GiDzHuczBgJk6DHiKDfoFQPjnOD19NGKqfvtvJCSsoK+IPl3wJ7GIdQ0YSWqBjc0q9S1sjprv4uNplAPAViM6euMBbEWsI51RVa8BxxMUICKLUUcPadbOAJ8k9l8DtOPPZ8+BsPxM6dhc6Fj2WNbz+SbsZYQ089X8BjznC9ppemAOeIcOgOFKoxiVpQ+fMbacOuz4kcnY8EtbfsmZlYPdRVqdqkYg25J4/1rkWo60st6fFC3ttf1+9c7bv+LKGTGTrF0smpcMcaWDUN9pPxWCvgyFukSkb8ebtqcME2UGWSByNlHs+mrLyWCu9dO1Wh779UA/wZXEpfvC/v2Y1cYi4N2THaHgOSyfrvFCyVN/XjCbdv2e5WLDGJdXAUuLVeYihOM8SaXJ9ZE3RII+6PpGZ6Y32z9EiwKEZWKXZABx2fCFtH2HNEOBiHRBtGfbJAFYySSBT+VlfxGBPvFjsdJrMfKU0kIeogOPemkCcbLiq9HWmDUvbzRhkMA5kgmEJZMp7q+b/6bAb0c9FWYPI0i/WJCqu5W2eA=
  file: $BASENAME-osx.zip
  on:
    repo: alterego2/titanium_mobile
